<div class="content-wrapper my-2">
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-md-6">
                    <strong class='text-danger'>
                        XIN CHÀO : <?php echo $this->login->fullname; ?>
                    </strong>
                </div>
            </div>
        </div>

        <div class="card-body">
            <div class="row">
                <div class="col-md-4"><img width="100%" height="100%"
                                           src="<?php echo $this->adminImgUrl . '/' . $this->login->img; ?>" alt="">
                </div>
                <div class="col-md-8">
                    <p><b> Tài khoản: </b><?php echo $this->login->username; ?></p>
                    <p><b> Họ tên: </b> <?php echo $this->login->fullname; ?></p>
                    <p><b> Email: </b> <?php echo $this->login->email; ?></p>
                    <p><b> Giới tính: </b> <?php $gender =  ($this->login->gender) ? 'Nam' : 'Nữ' ; echo $gender ;?></p>
                    <p><b> Số điện thoại: </b> <?php echo $this->login->phone; ?></p>
                </div>
            </div>
        </div>
    </div>
</div>
