<?php $this->doctype(); ?>
<header class="header-area clearfix">
    <!-- Close Icon -->
    <div class="nav-close">
        <i class="fa fa-close" aria-hidden="true"></i>
    </div>
    <!-- Logo -->
    <div class="logo">
        <a href="<?php echo $this->baseUrl('/user')?>"><img src="<?php echo $this->imgUrl; ?>/core-img/logo.png" alt=""></a>
    </div>
    <!-- Amado Nav -->
    <nav class="amado-nav">
        <ul>
            <li class="active"><a href="<?php echo $this->baseUrl('/user')?>">Home</a></li>
            <li><a href="<?php echo $this->baseUrl('/product')?>">Shop</a></li>
            <li><a href="product-details.html">Product</a></li>
            <li><a href="cart.html">Cart</a></li>
            <li><a href="checkout.html">Checkout</a></li>
        </ul>
    </nav>
    <!-- Button Group -->
    <div class="amado-btn-group mt-30 mb-100">
        <?php
        $auth = Zend_Auth::getInstance();
        if ($auth->hasIdentity()) {
            $info = $auth->getIdentity();
            ?>
            <a href="#" class="btn amado-btn mb-15">Hi <?php echo $info->fullname?></a>
            <a href="<?php echo $this->baseUrl('account/index/logout')?>" class="btn amado-btn active">Logout</a>
            <?php
        } else {
            ?>
            <a href="<?php echo $this->baseUrl('account/')?>" class="btn amado-btn active">Login</a>
            <?php
        }
        ?>

    </div>
    <!-- Cart Menu -->
    <div class="cart-fav-search mb-100">
        <a href="cart.html" class="cart-nav"><img src="<?php echo $this->imgUrl; ?>/core-img/cart.png" alt=""> Cart <span>(0)</span></a>
        <a href="#" class="fav-nav"><img src="<?php echo $this->imgUrl; ?>/core-img/favorites.png" alt=""> Favourite</a>
        <a href="#" class="search-nav"><img src="<?php echo $this->imgUrl; ?>/core-img/search.png" alt=""> Search</a>
    </div>
    <!-- Social Button -->
    <div class="social-info d-flex justify-content-between">
        <a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
        <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
        <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
        <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
    </div>
</header>
