<?php
$data = $this->rows;
var_dump($data); die();
?>
<div class="content-wrapper my-2">
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-md-6">
                    <strong class='text-danger'>
                        DANH SÁCH DANH MỤC
                    </strong>
                </div>
                <div class="col-md-6 text-right">
                    <a class="btn btn-sm btn-success" href="#"><i class="fas fa-plus-circle"></i>Thêm</a>
                    <a class="btn btn-sm btn-danger" href="#"><i class="fas fa-trash"></i>Thùng rác</a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <table id="myTable" class="table table-triped table-bordered table-hover">
                <thead class="thead-dark">
                <tr>
                    <th>Tên danh mục</th>
                    <th class="text-center">Chức năng</th>
                    <th class="text-center" style="width: 20px;">ID</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($data as $value) {?>
                <tr>
                    <td><?php echo $value['name']?></td>
                    <td class="text-center" style="padding-top: 35px">

                        <a class="btn btn-sm btn-success" href="#"><i class="fas fa-toggle-on"></i></a>

                        <a class="btn btn-sm btn-danger" href="#"><i class="fas fa-toggle-off"></i></a>

                        <a class="btn btn-sm btn-info" href="#"><i class="fas fa-edit"></i></a>
                        <a class="btn btn-sm btn-danger" href="#"><i class="fas fa-trash"></i></a>
                    </td>
                    <td class="text-center">1</td>
                </tr>
                <?php } ?>

                </tbody>
            </table>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
        $('#myTable').DataTable();
    });
</script>