<?php
$linkCat = $this->baseUrl($this->currentController . '/detail/id')
?>

<div class="products-catagories-area clearfix">
    <div class="amado-pro-catagory clearfix">

        <!-- Single Catagory -->
        <?php foreach ($this->Items as $value) :?>
        <div class="single-products-catagory clearfix">
            <a href="<?php echo $linkCat . '/' . $value['id'] ;?>">
                <img src="<?php echo $this->imgUrl . '/' . $value['img']; ?>" alt="">
                <!-- Hover Content -->
                <div class="hover-content">
                    <div class="line"></div>
                    <p>$ <del><?php echo $value['price']?></del>  $<?php echo $value['pricesale'];?></p>
                    <h4><?php echo $value['name']?></h4>
                </div>
            </a>
        </div>
        <?php endforeach; ?>


    </div>
</div>