<?php echo $this->render('html/header.phtml'); ?>
<body class="hold-transition sidebar-mini">
  <!-- Site wrapper -->
  <div class="wrapper">
    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
      <!-- Left navbar links -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
          <a href="../../../../index3.html" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
          <a href="index.php?option=contact" class="nav-link">Contact</a>
        </li>
      </ul>

      <!-- SEARCH FORM -->
      <form class="form-inline ml-3">
        <div class="input-group input-group-sm">
          <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-navbar" type="submit">
              <i class="fas fa-search"></i>
            </button>
          </div>
        </div>
      </form>

      <!-- Right navbar links -->
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
            <i class="fas fa-th-large"></i>
          </a>
        </li>
      </ul>
    </nav>
    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
      <!-- Brand Logo -->
      <a href="<?php echo $this->baseUrl('admin') ?>" class="brand-link">
        <img src="<?php echo $this->adminImgUrl; ?>/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light"><strong>HỆ THỐNG</strong></span>
      </a>

      <!-- Sidebar -->
      <div class="sidebar">
        <!-- Sidebar user (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
          <div class="image">
            <img src="<?php echo $this->adminImgUrl; ?>/avatar5.png" class="img-circle elevation-2" alt="User Image">
          </div>
          <div class="info">
            <a href="#" class="d-block"></a>
          </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
          <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
<!--            <li class="nav-item has-treeview">-->
<!--              <a href="#" class="nav-link">-->
<!--                <i class="nav-icon fas fa-tachometer-alt"></i>-->
<!--                <p>-->
<!--                  Sản Phẩm-->
<!--                  <i class="right fas fa-angle-left"></i>-->
<!--                </p>-->
<!--              </a>-->
<!--              <ul class="nav nav-treeview">-->
<!--                <li class="nav-item">-->
<!--                  <a href="--><?php //echo $this->baseUrl('admin/product/') ?><!--" class="nav-link">-->
<!--                    <i class="far fa-circle nav-icon"></i>-->
<!--                    <p>Danh sách sản phẩm</p>-->
<!---->
<!--                  </a>-->
<!--                </li>-->
<!--                <li class="nav-item">-->
<!--                  <a href="--><?php //echo $this->baseUrl('admin/category/') ?><!--" class="nav-link">-->
<!--                    <i class="far fa-circle nav-icon"></i>-->
<!--                    <p>Loại sản phẩm</p>-->
<!--                  </a>-->
<!--                </li>-->
<!--              </ul>-->
<!--            </li>-->


              <li class="nav-item">
                  <a href="<?php echo $this->baseUrl('admin/product/') ?>" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Danh sách sản phẩm</p>

                  </a>
              </li>

              <li class="nav-item">
                  <a href="<?php echo $this->baseUrl('admin/category/') ?>" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Loại sản phẩm</p>

                  </a>
              </li>
<!--            <li class="nav-item has-treeview">-->
<!--              <a href="#" class="nav-link">-->
<!--                <i class="nav-icon fas fa-copy" style="width:20px;"></i>-->
<!--                <p>-->
<!--                  Bài viết-->
<!--                  <i class="right fas fa-angle-left"></i>-->
<!--                </p>-->
<!--              </a>-->
<!--              <ul class="nav nav-treeview ">-->
<!--                <li class="nav-item">-->
<!--                  <a href="index.php?option=post" class="nav-link">-->
<!--                    <i class="nav-icon far fa-circle text-danger"></i>-->
<!--                    <p>Danh sách bài viết</p>-->
<!--                  </a>-->
<!--                </li>-->
<!--                <li class="nav-item">-->
<!--                  <a href="index.php?option=topic" class="nav-link">-->
<!--                    <i class="nav-icon far fa-circle text-danger"></i>-->
<!--                    <p>Chủ đề bài viết</p>-->
<!--                  </a>-->
<!--                </li>-->
<!--                <li class="nav-item">-->
<!--                  <a href="index.php?option=page" class="nav-link">-->
<!--                    <i class="nav-icon far fa-circle text-danger"></i>-->
<!--                    <p>Trang đơn</p>-->
<!--                  </a>-->
<!--                </li>-->
<!--              </ul>-->
<!--            </li>-->
<!--            <li class="nav-item">-->
<!--              <a href="index.php?option=order" class="nav-link">-->
<!--                <i class="nav-icon far fa-circle text-info"></i>-->
<!--                <p>Đơn hàng</p>-->
<!--              </a>-->
<!--            </li>-->
<!--            <li class="nav-item">-->
<!--              <a href="index.php?option=customer" class="nav-link">-->
<!--                <i class="nav-icon far fa-circle text-success"></i>-->
<!--                <p>Khách hàng</p>-->
<!--              </a>-->
<!--            </li>-->
<!--            <li class="nav-item">-->
<!--              <a href="index.php?option=contact" class="nav-link">-->
<!--                <i class="nav-icon far fa-circle text-danger"></i>-->
<!--                <p>Liên Hệ</p>-->
<!--              </a>-->
<!--            </li>-->
<!--            <li class="nav-item has-treeview">-->
<!--              <a href="#" class="nav-link">-->
<!--                <i class="nav-icon fas fa-chart-pie"></i>-->
<!--                <p>-->
<!--                  Giao diện-->
<!--                  <i class="fas fa-angle-left right"></i>-->
<!--                </p>-->
<!--              </a>-->
<!--              <ul class="nav nav-treeview">-->
<!--                <li class="nav-item">-->
<!--                  <a href="index.php?option=menu" class="nav-link">-->
<!--                    <i class="nav-icon far fa-circle text-danger"></i>-->
<!--                    <p>Menu</p>-->
<!--                  </a>-->
<!--                </li>-->
<!--                <li class="nav-item">-->
<!--                  <a href="index.php?option=slider" class="nav-link">-->
<!--                    <i class="nav-icon far fa-circle text-danger"></i>-->
<!--                    <p>slider</p>-->
<!--                  </a>-->
<!--                </li>-->
<!---->
<!--              </ul>-->
<!--            </li>-->
<!--            <li class="nav-item has-treeview">-->
<!--              <a href="#" class="nav-link">-->
<!--                <i class="nav-icon fas fa-chart-pie"></i>-->
<!--                <p>-->
<!--                  Hệ thống-->
<!--                  <i class="fas fa-angle-left right"></i>-->
<!--                </p>-->
<!--              </a>-->
<!--              <ul class="nav nav-treeview">-->
<!--                <li class="nav-item">-->
<!--                  <a href="index.php?option=user" class="nav-link">-->
<!--                    <i class="nav-icon far fa-circle text-danger"></i>-->
<!--                    <p>Thành viên</p>-->
<!--                  </a>-->
<!--                </li>-->
<!--                <li class="nav-item">-->
<!--                  <a href="index.php?option=user_insert" class="nav-link">-->
<!--                    <i class="nav-icon far fa-circle text-danger"></i>-->
<!--                    <p>Thêm thành viên</p>-->
<!--                  </a>-->
<!--                </li>-->
<!---->
<!--              </ul>-->
<!--            </li>-->


            <li class="nav-header">THÔNG TIN</li>
            <li class="nav-item">
              <a href="<?php echo $this->baseUrl('account/index/logout') ?>" class="nav-link">
                <i class="nav-icon far fa-circle text-danger"></i>
                <p class="text">Đăng xuất</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="" class="nav-link">
                <i class="nav-icon far fa-circle text-warning"></i>
                <p>Thông tin cá nhân</p>
              </a>
            </li>
          </ul>
        </nav>
      </div>
    </aside>
</body>

</html>

<?php echo $this->layout()->content ?>
<?php echo $this->render('html/footer.phtml'); ?>