<?php
$linkBack = $this->baseUrl($this->currentController . '/index');
$linkSave = $this->baseUrl($this->currentController . '/add');
?>
<style>
    #errors {
        background-color: darkorange;
        border: 1px solid;
    }
</style>
<form name="appForm" action="" method="post" enctype="multipart/form-data">
<div class="content-wrapper my-2">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-md-6">
                        <strong class='text-danger'>
                            THÊM THỂ LOẠI
                        </strong>
                    </div>
                    <div class="col-md-6 text-right">
                    <a class="btn btn-sm btn-success" href="#" onclick="OnSubmitForm('<?php echo $linkSave ?>')" ><i class="fas fa-plus-circle"></i>Lưu[Thêm]</a>
                        <a class="btn btn-sm btn-danger" href="<?php echo $linkBack ?>"><i class="fas fa-trash"></i>Thoát</a>
                    </div>
                </div>
            </div>
            <b><?php
                if ($this->messagesError != null) {
                    $errors = $this->formErrors($this->messagesError, array('id' => 'errors'));
                    echo $errors;
                }
                ?>
            </b>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-8">
                        <div class="form-group">
                            <label style="font-weight: bold;">Tên danh mục</label>
                            <input name="name" type="text" class="form-control" placeholder="Tên danh mục" required />
                        </div>
                        <div class="form-group">
                            <label style="font-weight: bold;">Trạng thái</label>
                            <select name="status" class="form-control">
                                <option value="1">Xuất bản</option>
                                <option value="2">Chưa xuất bản</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>