<?php
$row = $this->Item;
$linkBack = $this->baseUrl($this->currentController . '/index');
$linkEdit = $this->baseUrl($this->currentController . '/edit/id/' . $row['id']);

?>
<form name="appForm" action="" method="post" enctype="multipart/form-data">
    <div class="content-wrapper my-2">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-md-6">
                        <strong class='text-danger'>
                            SỬA THỂ LOẠI
                        </strong>
                    </div>
                    <div class="col-md-6 text-right">
                        <a class="btn btn-sm btn-success" href="#" onclick="OnSubmitForm('<?php echo $linkEdit ?>')"><i class="fas fa-plus-circle"></i>Lưu[Edit]</a>
                        <a class="btn btn-sm btn-danger" href="<?php echo $linkBack ?>"><i class="fas fa-trash"></i>Thoát</a>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-8">
                        <div class="form-group">
                            <label style="font-weight: bold;">Tên Thể loại</label>
                            <input name="name" type="text" value="<?php echo $row['name'] ?>" class="form-control" placeholder="tên sản phẩm" required />
                        </div>
                        <div class="form-group">
                            <label style="font-weight: bold;">Trạng thái</label>
                            <select name="status" class="form-control">
                                <option value="1" <?php echo ($row['status'] == 1) ? 'selected' : ''; ?>>Xuất bản</option>
                                <option value="0" <?php echo ($row['status'] == 0) ? 'selected' : ''; ?>>Chưa xuất bản</option>
                            </select>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    </div>
</form>