<?php
$linkAdd = $this->baseUrl($this->currentController . '/add');
$linkTrash = $this->baseUrl($this->currentController . '/trash');
$linkEdit = $this->baseUrl($this->currentController . '/edit/id');
$linkDelete = $this->baseUrl($this->currentController . '/delete/id');
?>
<div class="content-wrapper my-2">
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-md-6">
                    <strong class='text-danger'>
                        DANH SÁCH THỂ LOẠI
                    </strong>
                </div>
                <div class="col-md-6 text-right">
                    <a class="btn btn-sm btn-success" href="<?php echo $linkAdd; ?>"><i class="fas fa-plus-circle"></i>Thêm</a>
                    <a class="btn btn-sm btn-danger" href="<?php echo $linkTrash ?>"><i class="fas fa-trash"></i>Thùng rác</a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <table id="myTable" class="table table-triped table-bordered table-hover">
                <thead class="thead-dark">
                    <tr>
                        <th class="text-center" style="width: 20px;">ID</th>
                        <th>Tên thể loại</th>
                        <th class="text-center">Trạng thái</th>
                        <th class="text-center">Chức năng</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->Items as $key => $val) : ?>
                        <tr>
                            <td class="text-center"><?php echo $val['id']; ?></td>
                            <td><?php echo $val['name']; ?></td>
                            <td class="text-center" id="status-<?php echo $val['id'];?>" style="padding-top: 35px"><?php
                                $btn =  ($val['status'] == 1) ? 'btn-success' : 'btn-danger';
                                $icon =  ($val['status'] == 1) ? ' fa-toggle-on' : 'fa-toggle-off';

                                ?>
                                <a class="btn btn-sm <?php echo $btn?>" href="javascript:void(0)" onclick="restoreAjax(<?php echo $val['id'] . ',' . $val['status']; ?>)"><i class="fas <?php echo $icon?>"></i></a>
                            </td>
                            <td class="text-center" style="padding-top: 35px">
                                <a class="btn btn-sm btn-info" href="<?php echo $linkEdit . '/' . $val['id'] ?>"><i
                                            class="fas fa-edit"></i></a>
                                <a class="btn btn-sm btn-danger"  href="javascript:void(0)" onclick="deleteFunction(<?php echo $val['id']; ?>)"><i
                                            class="fas fa-trash"></i></a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
        $('#myTable').DataTable();
    });
</script>