<?php
$linkBack = $this->baseUrl($this->currentController . '/index');
$linkDel = $this->baseUrl($this->currentController . '/deltrash/id/');
$linkRestore = $this->baseUrl($this->currentController . '/restore/id/');
?>
<div class="content-wrapper my-2">
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-md-6">
                    <strong  class='text-danger'>
                        DANH SÁCH THỂ LOẠI RÁC
                    </strong>
                </div>
                <div class="col-md-6 text-right">
                    <a class="btn btn-sm btn-success" href="<?php echo $linkBack; ?>">
                        <i class="fas fa-reply">
                        </i>Quay lại</a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <table id = "myTable" class="table table-triped table-bordered table-hover">
                <thead class="thead-dark">
                    <tr>
                        <th class="text-center" style="width: 20px;">ID</th>
                        <th>Tên thể loại</th>
                        <th class="text-center">Chức năng</th>

                    </tr>
                </thead>
                <tbody>
                <?php foreach($this->Items  as $row) : ?>
                    <tr>
                        <td class="text-center"><?php echo $row['id']; ?></td>
                        <td><?php echo $row['name']; ?></td>
                        <td class="text-center" style="padding-top: 35px">
                        <a class="btn btn-sm btn-success" 
                        href="javascript:void(0)" onclick="restoretrashAjax(<?php echo $row['id'] ; ?>, 'category')"><i class="fas fa-trash-restore"></i></a>
                        <a class="btn btn-sm btn-danger" 
                        href="javascript:void(0)" onclick="deltrashAjax(<?php echo $row['id']; ?>, 'category')"><i class="fas fa-trash"></i></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
        $('#myTable').DataTable();
    });
</script>