<?php
$linkAdd = $this->baseUrl($this->currentController . '/add');
$linkTrash = $this->baseUrl($this->currentController . '/trash');
$linkEdit = $this->baseUrl($this->currentController . '/edit/id');
$linkDelete = $this->baseUrl($this->currentController . '/delete/id');
?>
<div class="content-wrapper my-2">
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-md-6">
                    <strong class='text-danger'>
                        DANH SÁCH SẢN PHẨM
                    </strong>
                </div>
                <div class="col-md-6 text-right">
                    <a class="btn btn-sm btn-success" href="<?php echo $linkAdd; ?>"><i class="fas fa-plus-circle"></i>Thêm</a>
                    <a class="btn btn-sm btn-danger" href="<?php echo $linkTrash ?>"><i class="fas fa-trash"></i>Thùng rác</a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <table id="myTable" class="table table-triped table-bordered table-hover">
                <thead class="thead-dark">
                    <tr>
                        <th>Hình ảnh</th>
                        <th>Tên sản phẩm</th>
                        <th class="text-center">Chức năng</th>
                        <th class="text-center" style="width: 20px;">ID</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->Items as $key => $val) : ?>
                        <tr>
                            <td class="text-center"><img width="200px" height="200px" src="<?php echo $this->adminImgUrl . '/' . $val['img']; ?>" alt=""></td>
                            <td><?php echo $val['name']; ?></td>
                            <td class="text-center" style="padding-top: 35px">
                                <?php if ($val['status'] == 1) {
                                ?>
                                    <a class="btn btn-sm btn-success" href="#"><i class="fas fa-toggle-on"></i></a>
                                <?php
                                } else { ?>

                                    <a class="btn btn-sm btn-danger" href="#"><i class="fas fa-toggle-off"></i></a>
                                <?php  } ?>
                                <a class="btn btn-sm btn-info" href="<?php echo $linkEdit . '/' . $val['id']?>" ><i class="fas fa-edit"></i></a>
                                <a class="btn btn-sm btn-danger" href="<?php echo $linkDelete . '/' . $val['id']?> "><i class="fas fa-trash"></i></a>
                            </td>
                            <td class="text-center"><?php echo $val['id']; ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
        $('#myTable').DataTable();
    });
</script>